### ISSUE TITLE
有好几处地方能改一下

### ISSUE THREAD

**Issue by CberYellowstone** [chengjieyong002/PikPakAutoOfflineDownloadBot#2]
1. 自定义TG API
2. 没考虑Aira2RPC有可能是https协议的
3. 文件地址拼接有误（两个`/`）
4. 有些地方能用更Pythonic的方法写

**Comment by chengjieyong002** [comment]
改写指正，我已看过你的pr，受益匪浅。但是第3条地址拼接错误是指`the_config['Aria2_download_path'] + '/' + path`这里吗？考虑到用户不一定会在ARIA2_DOWNLOAD_PATH的末尾带上`/`，并且即使此句可能`/`重复，仍然不影响aria2下载时创建的目录结构，所以我觉得可能加上更好

**Comment by CberYellowstone** [comment]
> 改写指正，我已看过你的 pr，受益匪浅。但是第 3 条地址拼接错误是指 `the_config ['Aria2_download_path'] + '/' + path` 这里吗？考虑到用户不一定会在 ARIA2_DOWNLOAD_PATH 的末尾带上 `/`，并且即使此句可能 `/` 重复，仍然不影响 aria2 下载时创建的目录结构，所以我觉得可能加上更好

其实我觉得 the_config 是没必要的，既然已经import * 了，那不如直接用config.py中的变量名

**Comment by CberYellowstone** [comment]
> `the_config` 最大的用处是 `login ()` 函数登陆的时候会给它赋以 `headers` 的键值对，并在其他 api 调用中均需用到 `headers` 对应的值。但是确实好像它的用处也仅是如此了。

那这样其实可以把 headers 单独作为一个全局变量，这样就可以了

**Comment by chengjieyong002** [comment]
> > `the_config` 最大的用处是 `login ()` 函数登陆的时候会给它赋以 `headers` 的键值对，并在其他 api 调用中均需用到 `headers` 对应的值。但是确实好像它的用处也仅是如此了。
> 
> 那这样其实可以把 headers 单独作为一个全局变量，这样就可以了

是的，我下个版本改吧。另外下个版本考虑加入账号管理功能，不用再通过修改config.py文件才能添加账号

**Comment by qweaszxcdf** [comment]
希望能加入多账户并行处理

**Comment by chengjieyong002** [comment]
> 希望能加入多账户并行处理

已纳入Todo，期待一下
