### ISSUE TITLE
启动的时候报错是什么情况呢

### ISSUE THREAD

**Issue by yoyosscn** [chengjieyong002/PikPakAutoOfflineDownloadBot#7]
python pikpakTgBot.py
  File "pikpakTgBot.py", line 15
SyntaxError: Non-ASCII character '\xe5' in file pikpakTgBot.py on line 15, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by chengjieyong002** [comment]
看起来是编码问题，可以尝试在`pikpakTgBot.py`首行加上`# -*- coding: utf-8 -*-`试一下能否解决。
但是我更建议检查`python`版本，需要保证`python`版本`＞=3.7`，运行命令`python -V`检查python版本

**Comment by yoyosscn** [comment]
升级完运行没有那个错误了 但是出现了一个错误是缺少了模块
Traceback (most recent call last):
  File "pikpakTgBot.py", line 2, in <module>
    from telegram.ext import Updater, CallbackContext, CommandHandler, MessageHandler, Filters
ModuleNotFoundError: No module named 'telegram'

**Comment by yoyosscn** [comment]
升级完运行没有那个错误了 但是出现了一个错误是缺少了模块

现在倒是解决刚刚那个问题了 但是又重新了一个缺少模块的问题 这个我已经安装了依赖 原因不明
Traceback (most recent call last):
  File "pikpakTgBot.py", line 2, in <module>
    from telegram.ext import Updater, CallbackContext, CommandHandler, MessageHandler, Filters
ModuleNotFoundError: No module named 'telegram'

**Comment by chengjieyong002** [comment]
这应该是由于pip与python不对应导致的，运行`pip -V`可以查看你的pip对应的是环境里的哪个python。
如果觉得上述操作都很麻烦，可以考虑使用`miniconda`，可以非常简单管理python环境，google搜索`miniconda`即可。或者期待将发布的docker版本。

**Comment by yoyosscn** [comment]
好的 谢谢！
